config/routes.rb
UserAuth::Application.routes.draw do

  root to: 'users#new'

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password
  validates :email, :presence => true
  validates_format_of :email, :with => /@/
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    render_unauthorized and return unless params[:email]
    user = User.where(email: params[:email]).first
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      # invalid password
      render_unauthorized
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private

    def render_unauthorized
      render status: 401, text: "401 Unauthorized"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def show
    @logged_in_user = User.find(session[:user_id])
  end

  def create
    @user = User.new params[:user]
    if @user.save
      session[:user_id] = @user.id
    else
      render status: 401, text: '401 and I hate your face' and return
    end
    redirect_to @user
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserAuth</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for :user, url: users_path do |f| %>
    <%= f.text_field :email, placeholder: "email" %>
    <%= f.text_field :password, placeholder: "password", type: "password" %>

    <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<%= link_to 'Sign out', session_path, method: :delete, data: { confirm: 'Are u sure?' }%>

<h1>hello, <%= @logged_in_user.email %></h1>